spring:
  application:
    name: MS3-spring-mail-appender

  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always