#SERVICE NAME
spring.application.name=EUREKA-SERVICE.COM

#PORT DETAILS
server.port=8791

#EUREKA LOCATION FOR REGISTRY
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# By default, the eureka registry is set to true
##DISABLE EUREKA REGISTRY
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false