server.port=8791

spring.application.name=EUREKA-LOAD-BALANCER-CART-SERVICE.COM

eureka.client.eureka-service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.instance-id=${spring.application.name}:${random.value}
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true